import 'typeface-just-another-hand'
import 'typeface-open-sans'
import 'typeface-rock-salt'
import 'tailwindcss/dist/base.css'
import 'tailwindcss/dist/components.css'
import 'tailwindcss/dist/utilities.css'
